language: node_js

git: 
    depth: 3 

node_js:
    - '10'

branches:
    only:
    - master
    - feature
    - fix

cache:
    directories:
        - node_modules
        - ~/.npm

notifications:
    email:
        recipients:
            - andreselias2303@gmail.com
        on_success: always
        on_failure: always
        
