language: node_js

git: 
    depth: 3 

node_js:
    - '10'

branches:
    only:
    - master
    - feature
    - fix

scripts:
    - yarn deploy

cache:
    directories:
        - node_modules
        - ~/.npm
        
